export interface MenuItem {
  name: string;
  price: number;
  category: string;
  ingredients?: string[];
  duplo?: number;
  isSandwich?: boolean;
}

export const menuData: Record<string, MenuItem[]> = {
  "🍔 Hambúrguers": [
    {
      name: "Juke Burguer",
      price: 25,
      category: "Hambúrguers",
      isSandwich: true,
      ingredients: [
        "Pão",
        "Queijo",
        "Hambúrguer artesanal de carne",
        "Maionese caseira",
        "Tomate",
        "Cebola crocante",
        "Anéis de cebola",
      ],
    },
    {
      name: "Burguer Duplo",
      price: 30,
      category: "Hambúrguers",
      isSandwich: true,
      ingredients: [
        "Pão",
        "Queijo",
        "Dois hambúrguers",
        "Maionese da casa",
        "Tomate",
        "Crispy de cebola",
        "Onion rings",
        "Molho billy jack",
      ],
    },
    {
      name: "Juke Bacon",
      price: 27,
      category: "Hambúrguers",
      isSandwich: true,
      ingredients: [
        "Pão",
        "Queijo",
        "Hambúrguer artesanal",
        "Tiras de bacon",
        "Barbecue",
        "Tomate",
        "Crispy de cebola",
        "Onion rings",
      ],
    },
    {
      name: "Duplo Bacon",
      price: 32,
      category: "Hambúrguers",
      isSandwich: true,
      ingredients: [
        "Pão",
        "Queijo",
        "Dois hambúrguers",
        "Tiras de bacon",
        "Barbecue",
        "Tomate",
        "Crispy de cebola",
        "Onion rings",
      ],
    },
    {
      name: "Juke Pernil com Abacaxi",
      price: 28,
      duplo: 33,
      category: "Hambúrguers",
      isSandwich: true,
      ingredients: [
        "Pão",
        "Queijo",
        "Pernil",
        "Maionese",
        "Abacaxi em pedaços",
        "Tomate",
        "Cebola crocante",
        "Anéis de cebola",
      ],
    },
    {
      name: "Vegetariano",
      price: 27,
      duplo: 32,
      category: "Hambúrguers",
      isSandwich: true,
      ingredients: [
        "Pão",
        "Hambúrguer vegetariano",
        "Maionese caseira",
        "Picles",
        "Alface",
        "Tomate",
        "Crispy de cebola",
        "Anéis de cebola",
      ],
    },
    {
      name: "Juke Costela",
      price: 29,
      duplo: 34,
      category: "Hambúrguers",
      isSandwich: true,
      ingredients: [
        "Pão",
        "Queijo",
        "Hambúrguer de costela",
        "Tomate",
        "Molho barbecue",
        "Crispy de cebola",
        "Onion rings",
      ],
    },
    {
      name: "Juke Frango",
      price: 27,
      duplo: 32,
      category: "Hambúrguers",
      isSandwich: true,
      ingredients: [
        "Pão",
        "Queijo",
        "Hambúrguer de frango",
        "Onion ring",
        "Alface",
        "Tomate",
        "Cebola crocante",
        "Maionese caseira",
      ],
    },
  ],
  "🍟 Porções": [
    { name: "Fritas 180g", price: 13, category: "Porções" },
    { name: "Fritas 400g + Cheddar + Bacon", price: 35, category: "Porções" },
    { name: "Aipim", price: 13, category: "Porções" },
    { name: "Polenta", price: 13, category: "Porções" },
    { name: "Bolinha de Queijo", price: 17, category: "Porções" },
    { name: "Mini Coxinha", price: 17, category: "Porções" },
    { name: "Quibe", price: 17, category: "Porções" },
    { name: "Onion Rings", price: 17, category: "Porções" },
    { name: "Nuggets", price: 18, category: "Porções" },
    { name: "Churros", price: 18, category: "Porções" },
    { name: "Amendoim", price: 6, category: "Porções" },
  ],
  "➕ Adicionais": [
    { name: "Cheddar", price: 3, category: "Adicionais" },
    { name: "Bacon", price: 3, category: "Adicionais" },
    { name: "Maionese da Casa", price: 2, category: "Adicionais" },
  ],
  "🍺 Chopes": [
    { name: "Pilsen", price: 12, category: "Chopes" },
    { name: "IPA Loka", price: 17, category: "Chopes" },
    { name: "Avelã Porter", price: 16, category: "Chopes" },
    { name: "Chope de Vinho", price: 12, category: "Chopes" },
    { name: "Chope Ice", price: 12, category: "Chopes" },
  ],
  "🥃 Shots": [
    { name: "Jambu", price: 16, category: "Shots" },
    { name: "Tequiloka", price: 12, category: "Shots" },
    { name: "Rabo de Galo", price: 10, category: "Shots" },
    { name: "Conhaque", price: 9, category: "Shots" },
    { name: "Jack Daniels", price: 24, category: "Shots" },
    { name: "Rum", price: 10, category: "Shots" },
    { name: "Licor 43", price: 23, category: "Shots" },
    { name: "Fernet", price: 12, category: "Shots" },
    { name: "Fire Ball", price: 23, category: "Shots" },
    { name: "Jagermeister", price: 23, category: "Shots" },
    { name: "Fire Licor Canela", price: 13, category: "Shots" },
    { name: "Niña Licor de Banana", price: 13, category: "Shots" },
    { name: "Campari", price: 13, category: "Shots" },
    { name: "Vodka Hambre", price: 15, category: "Shots" },
  ],
  "🍹 Drinks": [
    { name: "Quentão", price: 12, category: "Drinks" },
    { name: "Cuba Libre", price: 16, category: "Drinks" },
    { name: "Jambu Tônica", price: 22, category: "Drinks" },
    { name: "Jambu Libre", price: 22, category: "Drinks" },
    { name: "Gim Tônica", price: 22, category: "Drinks" },
    { name: "Moscow Mule", price: 23, category: "Drinks" },
    { name: "Moscow Mule Red", price: 23, category: "Drinks" },
    { name: "Pink Vodka Limonade", price: 23, category: "Drinks" },
    { name: "Jack and Coke", price: 30, category: "Drinks" },
    { name: "Vodka com Energético", price: 22, category: "Drinks" },
    { name: "Jager Bomb", price: 28, category: "Drinks" },
    { name: "Jager Hunter's Tea", price: 28, category: "Drinks" },
    { name: "Negroni", price: 22, category: "Drinks" },
  ],
  "🚫 Sem Álcool": [
    { name: "Soda Italiana", price: 16, category: "Sem Álcool" },
    { name: "Italian Spritz", price: 16, category: "Sem Álcool" },
    { name: "Refri, Suco e Mate", price: 7, category: "Sem Álcool" },
    { name: "Água", price: 5, category: "Sem Álcool" },
  ],
  "🍋 Caipirinhas": [
    {
      name: "Caipirinha de Limão",
      price: 15,
      category: "Caipirinhas",
    },
    {
      name: "Caipirinha de Abacaxi",
      price: 15,
      category: "Caipirinhas",
    },
    {
      name: "Caipirinha de Morango",
      price: 15,
      category: "Caipirinhas",
    },
    {
      name: "Caipirinha de Maracujá",
      price: 15,
      category: "Caipirinhas",
    },
    {
      name: "Caipirinha de Vinho",
      price: 20,
      category: "Caipirinhas",
    },
    {
      name: "Caipirinha de Jambu",
      price: 20,
      category: "Caipirinhas",
    },
    {
      name: "Caipirinha Materinha",
      price: 20,
      category: "Caipirinhas",
    },
  ],
  "🐂 Red Bull Combos": [
    { name: "Vodka & Red Bull", price: 30, category: "Red Bull Combos" },
    { name: "Meia Sete (Gin + Red Bull Sugarfree)", price: 30, category: "Red Bull Combos" },
    { name: "Tropical Gin (Gin + Red Bull Tropical)", price: 30, category: "Red Bull Combos" },
    { name: "Melancita (Gin + Red Bull Melancia)", price: 30, category: "Red Bull Combos" },
    { name: "Red Bull", price: 16, category: "Red Bull Combos" },
  ],
};
